"""Add onboarding fields to users table

Revision ID: 3a91fac28ea8
Revises: 667e821ac5b8
Create Date: 2025-07-02 19:49:42.741247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a91fac28ea8'
down_revision: Union[str, None] = '667e821ac5b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_files_v2',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_chapters_kid'), table_name='chapters_v1')
    op.drop_column('chapters_v1', 'language')
    op.drop_constraint(op.f('media_knowledge_fk'), 'media', type_='foreignkey')
    op.alter_column('roleplay_scenarios', 'language',
               existing_type=sa.VARCHAR(length=48),
               server_default=None,
               existing_nullable=True)
    op.alter_column('roleplay_scenarios', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_events', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_events', 'ts',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_user_events_data_gin'), table_name='user_events', postgresql_using='gin')
    op.drop_index(op.f('idx_user_events_user_ts'), table_name='user_events')
    op.alter_column('user_events', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('user_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.add_column('users', sa.Column('password_hash', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('grade_level', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('subjects_of_interest', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('learning_goals', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('preferred_difficulty', sa.String(length=20), nullable=True, server_default='medium'))
    op.add_column('users', sa.Column('school_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('subjects_taught', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('grade_levels_taught', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('years_experience', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('classroom_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'classroom_size')
    op.drop_column('users', 'years_experience')
    op.drop_column('users', 'grade_levels_taught')
    op.drop_column('users', 'subjects_taught')
    op.drop_column('users', 'school_name')
    op.drop_column('users', 'preferred_difficulty')
    op.drop_column('users', 'learning_goals')
    op.drop_column('users', 'subjects_of_interest')
    op.drop_column('users', 'grade_level')
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'password_hash')
    op.alter_column('user_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('user_events', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('idx_user_events_data_gin'), 'user_events', ['data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_user_events_user_ts'), 'user_events', ['user_id', 'ts'], unique=False)
    op.alter_column('user_events', 'ts',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('user_events', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('roleplay_scenarios', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('roleplay_scenarios', 'language',
               existing_type=sa.VARCHAR(length=48),
               server_default=sa.text("'English'::character varying"),
               existing_nullable=True)
    op.create_foreign_key(op.f('media_knowledge_fk'), 'media', 'knowledge', ['knowledge_id'], ['id'], ondelete='CASCADE')
    op.add_column('chapters_v1', sa.Column('language', sa.VARCHAR(length=48), server_default=sa.text("'English'::character varying"), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_chapters_kid'), 'chapters_v1', ['knowledge_id'], unique=False)
    op.drop_table('media_files_v2')
    op.drop_table('llm_usage_logs')
    # ### end Alembic commands ###
