"""Add password_hash to users table

Revision ID: 487e1be75dc3
Revises: 5a55b0db5000
Create Date: 2025-06-16 21:17:36.934027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '487e1be75dc3'
down_revision: Union[str, None] = '5a55b0db5000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_chapters_kid'), table_name='chapters_v1')
    op.drop_column('chapters_v1', 'language')
    op.drop_constraint(op.f('media_knowledge_fk'), 'media', type_='foreignkey')
    op.alter_column('roleplay_scenarios', 'language',
               existing_type=sa.VARCHAR(length=48),
               server_default=None,
               existing_nullable=True)
    op.alter_column('roleplay_scenarios', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_events', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_events', 'ts',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_events', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_user_events_data_gin'), table_name='user_events', postgresql_using='gin')
    op.drop_index(op.f('idx_user_events_user_ts'), table_name='user_events')
    op.alter_column('user_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.add_column('users', sa.Column('password_hash', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.alter_column('user_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.create_index(op.f('idx_user_events_user_ts'), 'user_events', ['user_id', 'ts'], unique=False)
    op.create_index(op.f('idx_user_events_data_gin'), 'user_events', ['data'], unique=False, postgresql_using='gin')
    op.alter_column('user_events', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('user_events', 'ts',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('user_events', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('roleplay_scenarios', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('roleplay_scenarios', 'language',
               existing_type=sa.VARCHAR(length=48),
               server_default=sa.text("'English'::character varying"),
               existing_nullable=True)
    op.create_foreign_key(op.f('media_knowledge_fk'), 'media', 'knowledge', ['knowledge_id'], ['id'], ondelete='CASCADE')
    op.add_column('chapters_v1', sa.Column('language', sa.VARCHAR(length=48), server_default=sa.text("'English'::character varying"), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_chapters_kid'), 'chapters_v1', ['knowledge_id'], unique=False)
    # ### end Alembic commands ###
