"""Add name to knowledge table and setup media relationships

Revision ID: ffe7f8d5024d
Revises: 11cb42504258
Create Date: 2025-06-16 15:44:22.576949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffe7f8d5024d'
down_revision: Union[str, None] = '11cb42504258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_analytics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('edtech_content', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('edtech_content', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('ix_edtech_content_chapter_id'), table_name='edtech_content')
    op.drop_index(op.f('ix_edtech_content_knowledge_id'), table_name='edtech_content')
    op.drop_index(op.f('ix_edtech_content_language'), table_name='edtech_content')
    op.drop_constraint(op.f('uq_edtech_content_chapter_language'), 'edtech_content', type_='unique')
    op.drop_constraint(op.f('edtech_content_chapter_id_fkey'), 'edtech_content', type_='foreignkey')
    op.drop_constraint(op.f('edtech_content_knowledge_id_fkey'), 'edtech_content', type_='foreignkey')
    op.create_foreign_key(None, 'edtech_content', 'knowledge', ['knowledge_id'], ['id'])
    op.create_foreign_key(None, 'edtech_content', 'chapters_v1', ['chapter_id'], ['id'])
    op.alter_column('engagement_metrics', 'views',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('engagement_metrics', 'completions',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('engagement_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    # Add name column as nullable first
    op.add_column('knowledge', sa.Column('name', sa.String(), nullable=True))
    
    # Update existing records with a default name based on their ID
    op.execute("UPDATE knowledge SET name = 'Knowledge Entry ' || id::text WHERE name IS NULL")
    
    # Make the column non-nullable
    op.alter_column('knowledge', 'name', nullable=False)
    op.alter_column('media', 'upload_status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('media', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('media', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('ix_media_knowledge_id'), table_name='media')
    op.drop_index(op.f('ix_media_upload_status'), table_name='media')
    op.drop_index(op.f('ix_media_uploaded_by'), table_name='media')
    op.alter_column('performance_stats', 'error_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('performance_stats', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'roles',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'roles',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=False)
    op.alter_column('performance_stats', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('performance_stats', 'error_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.create_index(op.f('ix_media_uploaded_by'), 'media', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_media_upload_status'), 'media', ['upload_status'], unique=False)
    op.create_index(op.f('ix_media_knowledge_id'), 'media', ['knowledge_id'], unique=False)
    op.alter_column('media', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('media', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('media', 'upload_status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=True)
    op.drop_column('knowledge', 'name')
    op.alter_column('engagement_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('engagement_metrics', 'completions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('engagement_metrics', 'views',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.drop_constraint(None, 'edtech_content', type_='foreignkey')
    op.drop_constraint(None, 'edtech_content', type_='foreignkey')
    op.create_foreign_key(op.f('edtech_content_knowledge_id_fkey'), 'edtech_content', 'knowledge', ['knowledge_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('edtech_content_chapter_id_fkey'), 'edtech_content', 'chapters_v1', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_edtech_content_chapter_language'), 'edtech_content', ['chapter_id', 'language'])
    op.create_index(op.f('ix_edtech_content_language'), 'edtech_content', ['language'], unique=False)
    op.create_index(op.f('ix_edtech_content_knowledge_id'), 'edtech_content', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_edtech_content_chapter_id'), 'edtech_content', ['chapter_id'], unique=False)
    op.alter_column('edtech_content', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('edtech_content', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('content_analytics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###
